name: build-site

on:
  push:
    branches:
      - master

jobs:
  BuildSite:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version-file: pnpm-workspace.yaml
          cache: pnpm

      # Our own build / publish
      - run: .github/build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
