name: build-site

on:
  push:
    branches:
      - main

jobs:
  BuildSite:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v3
        with:
          cache: true
          require-lockfile: true
      - run: .github/build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
